/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import proyecto.Controles;
import proyecto.Guardados;
import proyecto.Jugador;

/**
 *
 * @author El Jonas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        cargarpartida.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                /*  // Iniciar la tarea de carga de la partida aquí
                // Supongamos que tu tarea de carga toma tiempo y puedes usar un hilo para manejarla
                Thread tareaCarga = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        Simula la tarea de carga
                        for (int i = 0; i <= 100; i++) {
                            try {
                                Thread.sleep(100); // Simula una tarea que toma tiempo
                            } catch (InterruptedException ex) {
                                ex.printStackTrace();
                            }
                            barra.setValue(i);
                        }
                    }
                });

                tareaCarga.start(); // Inicia el hilo para la tarea de carga*/

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nuevaMascota = new javax.swing.JButton();
        cargarpartida = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        clave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 330, 80));

        nuevaMascota.setBackground(new java.awt.Color(153, 255, 255));
        nuevaMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo-producto.png"))); // NOI18N
        nuevaMascota.setText("Nueva Mascota");
        nuevaMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevaMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevaMascotaMouseClicked(evt);
            }
        });
        nuevaMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaMascotaActionPerformed(evt);
            }
        });
        jPanel1.add(nuevaMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, -1, -1));

        cargarpartida.setBackground(new java.awt.Color(153, 255, 255));
        cargarpartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cargando.png"))); // NOI18N
        cargarpartida.setText("Cargar Partida");
        cargarpartida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cargarpartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarpartidaMouseClicked(evt);
            }
        });
        cargarpartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarpartidaActionPerformed(evt);
            }
        });
        jPanel1.add(cargarpartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        salir.setBackground(new java.awt.Color(153, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        salir.setText("Salir");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setText("Usuario:");

        usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(usuario)
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 280, 40));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));

        jLabel3.setText("Contraseña:");

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clave, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clave)
                .addGap(9, 9, 9))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 300, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo onmon_1.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaMascotaActionPerformed
        Guardados g = new Guardados();

        this.dispose();
        Registrarse r = new Registrarse();
        r.fecha.setText(g.fecha());
        r.setLocationRelativeTo(null);
        r.setVisible(true);
    }//GEN-LAST:event_nuevaMascotaActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked

    }//GEN-LAST:event_salirMouseClicked

    private void nuevaMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaMascotaMouseClicked


    }//GEN-LAST:event_nuevaMascotaMouseClicked

    private void cargarpartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarpartidaActionPerformed
        Guardados g = new Guardados();
        Jugador jugador = g.cargarPartida(this.usuario.getText(), this.clave.getText());
        if (jugador != null) {
            InterfaceSala sala = new InterfaceSala();
            this.dispose();
            sala.setLocationRelativeTo(null);
            System.out.println("Jugador con nombre: " + jugador.getNombre());
            System.out.println("Fecha: " + jugador.getUltima_Conexion());
            sala.omnom.setText(jugador.getMascota().getNombre());
            sala.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado");
        }

    }//GEN-LAST:event_cargarpartidaActionPerformed

    private void cargarpartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarpartidaMouseClicked

    }//GEN-LAST:event_cargarpartidaMouseClicked

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        JOptionPane.showMessageDialog(null, "Ha salido de la aplicacion");
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarpartida;
    private javax.swing.JPasswordField clave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton nuevaMascota;
    private javax.swing.JButton salir;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
